name: QA Automation CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar Java 21 correctamente
        run: |
            sudo apt update
            sudo apt install -y maven openjdk-21-jdk

            export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH

            echo "JAVA_HOME=$JAVA_HOME"
            java -version
            javac -version

            mvn -version